name: intercom_flutter
description: Flutter plugin for Intercom integration. Provides in-app messaging and help-center Intercom services
version: 2.0.1
author: Maido Käära <m@maido.io>
homepage: https://github.com/v3rm0n/intercom_flutter

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: io.maido.intercom
    pluginClass: IntercomFlutterPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.5.0 <2.0.0"
